[workspace]
members = ["client", "proto", "server"]

[workspace.dependencies]
prost = "0.11"
tonic = "0.9"
tonic-build = "0.9"
tokio = { version = "1.28", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"
