[package]
name = "server"
version = "0.2.0"
edition = "2021"

[dependencies]
proto = { path = "../proto" }
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
