[package]
name = "server"
version = "0.1.1"
edition = "2021"

[dependencies]
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
proto = { path = "../proto" }
uuid = { version = "1.3", features = ["v4", "fast-rng", "macro-diagnostics"] }
